### ISSUE TITLE
Activation by email

### ISSUE THREAD

**Issue by ugurcanlacin** [springboilerplate/spring-rest-security-boilerplate#4]
There is no any standard framework solution for this issue. So, we basically implement an algorithm.

- It must link back to the User (via a unidirectional relation)
- It will be created right after registration
- It will expire within 24 hours following its creation
- Has a unique, randomly generated value

After registration process, the system will send email to registered email. The email will have a verification code. So, User will copy that verification code and will send it to another Rest API.

There will be simple Rest API. It will take a String parameter, which is  verification code. 
And it will check if that verification code exist and not expired (24 hours.)
It will activate a user linked to that verification code. (User(activate) field will be true.)
After activation, verification code will be deleted.

You can get help from following link.
http://www.baeldung.com/registration-verify-user-by-email

**Comment by volkandgn** [comment]
This is not done yet, "After activation, verification code will be deleted." 
It will be considered during #5 issue
